In [1]:
import pandas as pd

In [17]:
df1 = pd.read_csv("../../../dataset_01_parceiroA.csv")
df2 = pd.read_csv("../../../dataset_02_parceiroB.csv")
df3 = pd.read_csv("../../../dataset_03_parceiroC.csv")
df4 = pd.read_csv("../../../dataset_teste_100_linhas_parceiro_unico.csv")

In [6]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data                276 non-null    str
 1   Grupos de usuários  276 non-null    str
 2   Parceiro            276 non-null    str
 3   compradores         276 non-null    int64
 4   comissão            276 non-null    str
 5   cashback            276 non-null    str
 6   vendas totais       276 non-null    str
dtypes: int64(1), str(6)
memory usage: 15.2 KB

In [7]:
df1.nunique()

Data                   92
Grupos de usuários      3
Parceiro                1
compradores           143
comissão              274
cashback              271
vendas totais         276
dtype: int64

In [8]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data                183 non-null    str
 1   Grupos de usuários  183 non-null    str
 2   Parceiro            183 non-null    str
 3   compradores         183 non-null    int64
 4   comissão            183 non-null    str
 5   cashback            183 non-null    str
 6   vendas totais       183 non-null    str
dtypes: int64(1), str(6)
memory usage: 10.1 KB

In [9]:
df2.nunique()

Data                   61
Grupos de usuários      3
Parceiro                1
compradores            94
comissão              181
cashback              181
vendas totais         183
dtype: int64

In [10]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Data                90 non-null     str
 1   Grupos de usuários  90 non-null     str
 2   Parceiro            90 non-null     str
 3   compradores         90 non-null     int64
 4   comissão            90 non-null     str
 5   cashback            90 non-null     str
 6   vendas totais       90 non-null     str
dtypes: int64(1), str(6)
memory usage: 5.1 KB

In [11]:
df3.nunique()

Data                  45
Grupos de usuários     2
Parceiro               1
compradores           57
comissão              89
cashback              87
vendas totais         90
dtype: int64

In [12]:
def normalize(info):
    return info.replace(".", '').replace(',','.')[3:]

In [13]:
df3['comissão'] = df3['comissão'].apply(normalize).astype(float)
df3['cashback'] = df3['cashback'].apply(normalize).astype(float)
df3['vendas totais'] = df3['vendas totais'].apply(normalize).astype(float)

In [15]:
df2['comissão'] = df2['comissão'].apply(normalize).astype(float)
df2['cashback'] = df2['cashback'].apply(normalize).astype(float)
df2['vendas totais'] = df2['vendas totais'].apply(normalize).astype(float)

In [16]:
df2.groupby('Grupos de usuários')[['comissão', 'cashback']].sum()

                    comissão  cashback
Grupos de usuários
Grupo 1             450321.0  163751.0
Grupo 2             314935.0  171778.0
Grupo 3             289290.0  236697.0

In [19]:
df4['comissão'] = df4['comissão'].apply(normalize).astype(float)
df4['cashback'] = df4['cashback'].apply(normalize).astype(float)
df4['vendas totais'] = df4['vendas totais'].apply(normalize).astype(float)

AttributeError: 'float' object has no attribute 'replace'

In [20]:
df4.groupby('Grupos de usuários')[['comissão', 'cashback']].sum()

                    comissão  cashback
Grupos de usuários
Grupo 1             251220.0  119709.0
Grupo 2             165758.0   84652.0
Grupo 3             200545.0  108660.0
Grupo 4             256722.0  137871.0